### ISSUE TITLE
Version conflict error

### ISSUE THREAD

**Issue by nazrulworld** [plone/guillotina#111]
I am trying to run buildout from master branch after pull latest.
Unfortunately got version conflict error, coming from buildout.

```
............................................................
...............................................................
Version and requirements information containing urllib3:
  Requirement of aio_etcd: urllib3>=1.7.1
  Requirement of requests!=2.11.0,!=2.12.2,!=2.18.0,>=2.5.2: urllib3<1.22,>=1.21.1
  Requirement of python-etcd: urllib3>=1.7.1
While:
  Installing pytest.
Error: There is a version conflict.
We already have: urllib3 1.22
but requests 2.18.1 requires 'urllib3<1.22,>=1.21.1'.

``` 
I could fix this problem by pinning urillib3 version of 1.21.1 into buildout.cfg, but may be that is not the best solution.
Looking forward :)

**Comment by vangheem** [comment]
Pinning is completely fine.

**Comment by vangheem** [comment]
https://github.com/plone/guillotina/commit/594a5fc84bb52d50bb60de3f8aa45d1b8bb9756c
