### ISSUE TITLE
Supporting versions of an API

### ISSUE THREAD

**Issue by tomgross** [plone/guillotina#168]
How would I implement several versions (aspects) of an API with the containerish architecture of Guillotina?

Let's say I have a container with content and put a service on it. This is straight forward: `containter/@service` 

Now what I want is `container/v1/@service` and `container/v2/@otherservice`.

Putting the version name in the service name (like `container/@v1_service`) does not work in all situations because there might be legacy names I can't/want to change.

Does sound adding a noop Container with the version as the name and access the items from its parent sound feasable, or this there another recommended way to do it?

**Comment by vangheem** [comment]
There is no elegant way right now and I think the best way would be something like:

- have api versions 1 and 2 in different modules
- run 2 configurations, one for each app, on different ports
- use virtual host configuration with a proxy to prefix urls v1 or v2

This reminds me also that we should think about providing some built-in ability to mount apps at prefixes. It's already part of aiohttp, we just need to support it.

**Comment by vangheem** [comment]
Another option would be for guillotina to be able to hook into the traversal framework so you could provide your own traverse method maybe.

However, I think what would work best for your situation and provide the best general use-case is something like a named url segment. It'd behave like a service but allow further traversing.

something like...
```
@configure.named_url_segment(
    name="v1",
    context=IContainer,
    permission="guillotina.AccessContent")
async def v1(container, request):
    return container
```

**Comment by tomgross** [comment]
@vangheem Thanks for your answer. Hooking into the traversal framework sounds like a clean and generic approach too me.

**Comment by vangheem** [comment]
Hi @tomgross!

Would you be able to review https://github.com/plone/guillotina/pull/174 ?

It basically just allows customizing the router class with your own.

Then, for your use-case, you could do something like:

```
from guillotina import configure
from guillotina.content import Resource
from guillotina.interfaces import IContainer
from guillotina.interfaces import IDefaultLayer
from guillotina.interfaces import IRequest
from guillotina.interfaces import IResource
from guillotina.traversal import TraversalRouter
from guillotina.traversal import traverse
from zope.interface import alsoProvides


class IV1Layer(IDefaultLayer):
    pass


class IV2Layer(IDefaultLayer):
    pass


@configure.service(method='GET', name='@foobar',
                   permission='guillotina.AccessContent',
                   layer=IV1Layer)
async def v1_service(context, request):
    return {
        'version': '1'
    }


@configure.service(method='GET', name='@foobar',
                   permission='guillotina.AccessContent',
                   layer=IV2Layer)
async def v2_service(context, request):
    return {
        'version': '2'
    }


@configure.contenttype(type_name="VersionRouteSegment")
class VersionRouteSegment(Resource):

    type_name = 'VersionRouteSegment'

    def __init__(self, name, parent):
        super().__init__()
        self.__name__ = self.id = name
        self.__parent__ = parent


class MyRouter(TraversalRouter):
    async def traverse(self, request: IRequest) -> IResource:
        resource, tail = await super().traverse(request)
        if len(tail) > 0 and tail[0] in ('v1', 'v2') and IContainer.providedBy(resource):
            segment = VersionRouteSegment(tail[0], resource)
            if tail[0] == 'v1':
                alsoProvides(request, IV1Layer)
            elif tail[0] == 'v2':
                alsoProvides(request, IV2Layer)

            if len(tail) > 1:
                # finish traversal from here
                return await traverse(request, segment, tail[1:])
            else:
                resource = segment
                tail = tail[1:]
        return resource, tail


app_settings = {
    # provide custom application settings here...
    'router': MyRouter
}
```

Long term, I still might consider something like the `@configure.named_url_segment` approach but this should work for you for now.
