### ISSUE TITLE
@items pagination is broken

### ISSUE THREAD

**Issue by cdevienne** [plone/guillotina#270]
The `@items` service filters out the result based on permissions.
The pagination is made prior to filtering, leading to exotic paging information in the final result.

**Comment by vangheem** [comment]
This is terrible. I regret implementing the endpoint now!

This is really something that should only be done with elasticsearch/postgresql search

**Comment by cdevienne** [comment]
Well, those searches will not handle permissions properly, will they ?

**Comment by vangheem** [comment]
Yes they do :) https://github.com/guillotinaweb/guillotina_elasticsearch/blob/master/guillotina_elasticsearch/utility.py#L150

**Comment by cdevienne** [comment]
I doubt this is enough as it the actual roles of the user on a given object cannot be taken into account.

**Comment by vangheem** [comment]
it's enough, we use it extensively

**Comment by vangheem** [comment]
If you change roles, you need to reindex, but all the logic is there for reindexing when permissions change.

**Comment by cdevienne** [comment]
What if a user has a role on a subresource, but not on the container ?
The roles passed to the query will not contain the role that may give access to the resource, and it will never be returned.

What if a user has a role on a folder but not its children, and this role gives the access permission? Won't the user get some resources it cannot access otherwise?

**Comment by vangheem** [comment]
These are calculated roles.

If roles/permissions change on the parent, all children get reindexed with changes.

**Comment by vangheem** [comment]
For any resource, you know the permissions required to access it. This is what is stored and queried against.

**Comment by vangheem** [comment]
and keep in mind, it's not just roles, it's users that have access to it.

So,

```
What if a user has a role on a subresource, but not on the container ?
```

would be covered with access_users, not access_roles

**Comment by cdevienne** [comment]
I had cases where a search returned resources my user should not have access to. Maybe we missed something but I really thought the system was not complete.

Now, if I understand correctly, access_users is generated from the roles and groups that have the access permissions?

**Comment by vangheem** [comment]
Yup, maybe you change a users roles/groups dynamically and the corresponding content doesn't get reindexed.

**Comment by vangheem** [comment]
Closing this as we're not going to fix this in core guillotina.

If anything, we will remove this endpoint and implement in guillotina_cms but core guillotina will not implement something like this because of the potential performance implications.
