### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#305]
"The full stack data framework"

1. Fast and scalable out of the box: scalability/performance/asyncio/micro services
2. Simplicity with batteries included, "the right amount of batteries", cors, es, etc, extensible
3. Securely organized data

# Why Guillotina

- **Performance**: Traditional python web servers limit the number of simultaneous
   requests to the number of threads running the server. With AsyncIO, you are
   able to server many simultaneous requests at the same time.
 - **Front-end friendly**: Guillotina is designed to make your
   JavaScript engineers happy. With things like automatic swagger documentation
   for endpoints, OOTB CORS and websockets, your front-end team will be happy
   to work with Guillotina. We speak JSON but can adapt with any Content-Type
   payload request/response bodies.
 - **AsyncIO**: With AsyncIO, websockets are simple. More interestingly, AsyncIO
   is an ideal match with micro-service architectures.
 - **Object model**: Guillotina uses a hierarchial object model. This hierarchy
   of objects then maps to URLs. The hierarchy model is perfect for managing
   a large number of objects.
 - **Security**: Guillotina has a granular, hierarchial, multi-demensional
   security system that allows you to manage the security of your content
   at a level not available to other frameworks.
 - **Scale**: With integrations like Redis, ElasticSearch and Cockroach, you
   have the tools to scale.

**Comment by tkimnguyen** [comment]
Is this in the docs now or on the website?

**Comment by vangheem** [comment]
little bit of both :)
