### ISSUE TITLE
InMemory cache. Scale Down

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#320]
Right now, guillotina is super stable and scales up well.
But there are use cases where you only want to deploy a single guillotina service, and with this there are additional missing features, like the object cache. (We know, we can use the redis one, but doesn't make sense to deploy a new service neither all the invalidations pubsub feature).
The main idea is to provide just an in-process lru-cache, that fills this gap.
I'm not sure if this should go to an additional package or just implement a new InMemory cache strategy.
Ideas, thoughts?

**Comment by jordic** [comment]
Seems like with the pubsub/cache integration this is already done!

**Comment by vangheem** [comment]
Woot!
