### ISSUE TITLE
Proposal: behavior aliases

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#330]
Instead of needing to reference complete behavior interfaces names, be able to register a behavior with an alias.

For example, a PATCH like this:

```
"guillotina.behaviors.dublincore.IDublinCore": {
                    "title": "foo",
                    "description": "bar",
                    "tags": ["one", "two"]
                }
```

Could be changed to:

```
"dublincore": {
                    "title": "foo",
                    "description": "bar",
                    "tags": ["one", "two"]
                }
```

Registering behavior would change to add "alias" option for the configurator.

**Comment by bloodbare** [comment]
What aproach would be then for the serialization ? The goal is to reduce the payload ?

**Comment by ebrehault** [comment]
It would make the object nicer on the frontend (always painful to write `res['guillotina.behaviors.dublincore.IDublinCore']`)

**Comment by bloodbare** [comment]
Agree that is painful to write the interfaces to access the subschemas, the question is how we normalize on serialization the different interfaces, I mean, if we define guillotina.behaviors.dublincore.IDublinCore to dublincore and there is a field on top called dublincore, how we will be deterministic about where the content belongs.

What about a definition of how a field that is a subschema is serialized and deserialized. Something like no option to have fields with 'b.' at the begining so we can use: b.dublincore ?

**Comment by vangheem** [comment]
@bloodbare conflicts would be rare I think but yes, produce a situation with unclear behavior.

I'm not sure about "b.dublincore" though.. hmmm. Also could do `@behavior.dublincore`...

I'd prefer just simple alias though.

**Comment by vangheem** [comment]
Another question: do we serialize with alias or with full dotted name?

**Comment by vangheem** [comment]
and is "alias" the right term. Should it just be "name"?

**Comment by vangheem** [comment]
I think I still want to do this. Any more thoughts on this? What about configuration validation so you can't have an alias that is a field or something like that?

**Comment by iham** [comment]
doesn't plone have something thats called a "named behavior" to make life easier with theses dotted names?

maybe i am missing the point, but a "guillotina.dublincore" or "g.dublincore" similar would be nice. way nicer then the whole dotted name.

**Comment by vangheem** [comment]
@iham I'm not aware of anything like this in plone. I'd prefer an alias over some sort of `g.dublincore` shortened version though.

**Comment by jensens** [comment]
For Plone we introduced behavior shortnames a while ago and use them. plone.dublincore is a bad example (because composite behaviors are a bad idea, but thats different topic).

Look at https://docs.plone.org/external/plone.app.dexterity/docs/reference/standard-behaviours.html for a list of the names.

Using a namespace prefix like `plone.` is a good idea, but using the dotted name not. Refactoring, moving interfaces around and so on becomes painful then. Also its very difficult to remember those long names.

**Comment by vangheem** [comment]
awesome! thanks @jensens !

**Comment by vangheem** [comment]
closing, not doing for now.
