### ISSUE TITLE
Proposal: simplify behavior registration

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#332]
Be able to register a behavior by only defining a schema.

@bloodbare thoughts?

**Comment by bloodbare** [comment]
So you mean not defining the instance class? what is the final goal?

**Comment by vangheem** [comment]
To make the API easier.

Something like this:

```
from guillotina import schema
from zope import Interface
from guillotina import configure

@configure.behavior()
class IMyBehavior(Interface):
    foobar = schema.TextLine()
```

**Comment by bloodbare** [comment]
I understand the point, agree on adding the option that if the behavior decorator class inherits from Interface it creates a dummy instance class and still supporting the option to define the concrete instance class.
