### ISSUE TITLE
Heroku install?

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#337]
maybe we should have a simple heroku install that people can get up and running with

**Comment by AkshJain99** [comment]
@vangheem which application you are talking about to deploy 
on heroku?

**Comment by AkshJain99** [comment]
@vangheem on which framework backend of guillotina works on, because thats how we can depoly it on heroku

**Comment by AkshJain99** [comment]
should we need to deploy it or what i am not getting it , what we have to do to fix this issue

**Comment by AkshJain99** [comment]
@vangheem app is installed but it have some application error for which we can open up new issue

**Comment by vangheem** [comment]
it looks like gunicorn is trying to load wsgi app. guillotina is not wsgi--it is asyncio.

**Comment by vangheem** [comment]
It seems to me you need to run the regular server with configuration file not with trying with gunicorn.

With configuration like `guillotina:app`, gunicorn is expecting a configured wsgi app at module `guillotina` named `app`.

Just get it running with regular startup command `g -c config.yaml`

**Comment by AkshJain99** [comment]
@vangheem  then what should be mentioned in the procfile then
?

**Comment by vangheem** [comment]
Yes, I imagine so. I'm not super familiar with heroku though

**Comment by AkshJain99** [comment]
hm okay

**Comment by karannaoh** [comment]
hello, @vangheem I want to work on this issue, I have already installed guillotina [here](https://testguillotina.herokuapp.com/) . Please check

**Comment by vangheem** [comment]
@karannaoh great!

**Comment by vangheem** [comment]
Merged, thank you!
