### ISSUE TITLE
schema validations not being enforced on object creation

### ISSUE THREAD

**Issue by ericof** [plone/guillotina#374]
Using the example available at [the documentation](https://guillotina.readthedocs.io/en/latest/training/extending/contenttypes.html#content-types), after creation of Container with id *chats* and a Conversation with id *talks-0001* the creation of a new Message does not validate the payload against the schema.

**URI**: http://localhost:8080/db/chats/talk-0001
**Verb**: POST
**Payload**:
```
{
	"@type": "Message",
	"id": "msg-0002"
}
```

**content.py**
```
from guillotina import configure, content, Interface, schema


class IConversation(Interface):

    users = schema.List(
        value_type=schema.TextLine()
    )


@configure.contenttype(
    type_name="Conversation",
    schema=IConversation,
    behaviors=["guillotina.behaviors.dublincore.IDublinCore"],
    allowed_types=['Message'])
class Conversation(content.Folder):
    pass


class IMessage(Interface):
    text = schema.Text(required=True)


@configure.contenttype(
    type_name="Message",
    schema=IMessage,
    behaviors=[
        "guillotina.behaviors.dublincore.IDublinCore",
        "guillotina.behaviors.attachment.IAttachment"
    ])
class Message(content.Item):
    pass
```

**Comment by vangheem** [comment]
By default, Guillotina does not enforce validation of items not in the payload.

This is an optimization choice we made. Maybe the wrong choice and I'm open to handling it another way... but we didn't want to validate potentially very large schemas when you might only be patching a small part of it.

It's been reported before and I know this is different than plone/zope: https://github.com/plone/guillotina/issues/151

\cc @bloodbare

**Comment by ericof** [comment]
@vangheem Explained, I believe it is important to document this on the training materials

**Comment by vangheem** [comment]
I think we had a pr to fix this. closing
