### ISSUE TITLE
JSONAPI Standard

### ISSUE THREAD

**Issue by v3ss0n** [plone/guillotina#392]
Is there any https://jsonapi.org/ standard support planned?
Currently the format is quite different from json structures for EmberJS and other JSONApi supporting libs.

**Comment by vangheem** [comment]
We've been trying to follow https://plonerestapi.readthedocs.io/en/latest/ which follows json ld instead of json api.

https://json-ld.org/

Do you some example of how changing the api can improve usage for emberjs and other frameworks?

I'd be willing to rethink how we do it or provide some packages that make it easier to integrate.

For us, it's very simple to tweak how we render the the json data structures so we could provide some addon package that provided a different variant of the api if it's really useful.

**Comment by vangheem** [comment]
actually, we don't follow json ld very well. We really do a combo of json ld + json schema.

I guess we need to spend some time fixing our approach and documenting what we're trying to adhere to.

**Comment by v3ss0n** [comment]
we  are considering to migrate from rethinkdb + tornado  + Emberjs stack to Guiltotina
if it is easy to get JSONApi working in Guilllotina it would be awesome. Is there any pointers to make an addon to do so?

**Comment by vangheem** [comment]
A guillotina application that provided this functionality would basically be overriding the default content serializers.

For example, here is a guillotina application that customizes content serialization for a particular type: https://github.com/plone/guillotina_cms/blob/master/guillotina_cms/json/serialize_content.py#L42

In your case, you would be customizing the default for all content.

The base implementation is here: https://github.com/plone/guillotina/blob/master/guillotina/json/serialize_content.py#L37

I would recommend architecting an addon to customize in a manner like this:

```
@configure.adapter(
    for_=(IResource, Interface),
    provides=IResourceSerializeToJson)
class CustomSerializeToJson(SerializeToJson):

    @profilable
    async def __call__(self, include=[], omit=[]):
        data = await super().__call__(include, omit)
        result = {...}  # json api representation
        return result
```

Here are the docs for generating an app: https://guillotina.readthedocs.io/en/latest/developer/narrative.html#generating-the-initial-application

This could be a major oversimplification of the problem though!

**Comment by bloodbare** [comment]
@tisto  any two cents on this issue?

**Comment by vangheem** [comment]
Closing for now, please follow up any more comments related to it on https://github.com/plone/guillotina/issues/423
