### ISSUE TITLE
[Question] Share the asyncpg pool with other aio apps running on the same instance

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#421]
We have some other aio endpoints that will run on the same guillotina service, and I'm just trying to figure what's the best way of just share the asyncpg.pool. (On the end it's just because I don't want to have so many opened connections to postgres, we already have a lot of other services that are connected to postgres), and I don't want to setup and manage a pgpool.

I'm not super sure, how we can just get an instance of the pool (that lives on the postgresmanager), any hints on this will be good!

So many thanks!

**Comment by vangheem** [comment]
Hi Jordi!

Is it reasonable to get the storage object and ask for a connection directly from the pool when you're using your other services?

It would be something like this I think:

```
app = get_utility(IApplication, name='root')
storage = app['db'].storage
conn = storage.open()
# pool is available directly from storage.pool
```

Or did you have something else in mind?

**Comment by jordic** [comment]
Yes thats enought! Anyway, what I saw @allusa has done, is something like this:

```
@configure.subscriber(for_=IApplicationInitializedEvent)
async def app_init(event):
    try:
        pg_pool = event.app.root['db'].storage.pool
    except AttributeError:
        pg_pool = event.app.root['db'].storage
    app_auth = await main.create_app(serve_static=False,
                                     pg_engine=pg_pool
                                     )
```

**Comment by vangheem** [comment]
yup, that works as well!
