### ISSUE TITLE
Guillotina API Evolution

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#423]
- [ ] OpenAPI 3 support: Along with updating JSON schema validation support, we need to update our swagger documentation to work with OpenAPI 3/swagger 3.
- [ ] JSON schema validation: Right now, Guillotina supports JSON schema for content fields and validation; however, not all JSON bodies have JSON schema compliant validation. We need to validate all JSON payloads against well defined JSON schemas.
- [ ] Websocket API protocol: Fully support all API functionality through the websocket endpoint.
- [ ] API versioning: Provide a mechanism to version API endpoints. For example, prefixing all urls with `/v1`, `/v2` etc.
- [ ] plone.restapi compliance: It is also important that we coordinate with the plone.restapi so the APIs are similarly implemented.

**Comment by AkshJain99** [comment]
@vangheem what do you actually meant by last point ?
were not we already coordinated with plone.restapi?

**Comment by AkshJain99** [comment]
@vangheem as stated above that we have to create more comilant json LD api , so what i want to ask is that
do we need to make guillotina as JSON -LD or we need to add support of JSON-LD to guillotina
can you please Little bit elaborate this point?

**Comment by vangheem** [comment]
Last point: We need to try and make sure that any changes are also compliant with plone.restapi. They are to an extent right now but if we do changes, they won't be.

Guillotina is somewhat json-ld but not completely. I haven't done a full analysis to give point by point changes that we could make. Whoever works on this will need to analyze the Guillotina API as well as JSON LD standards and make recommendations are changes to take.

**Comment by AkshJain99** [comment]
@vangheem actually I am preparing the proposal but stuck on second task what actually second task is asking 
? Can you litte bit elaborate it? what all api are we talking about here to support through websocket endpoint
