### ISSUE TITLE
AnnotationBehavior with ContextProperty

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina#434]
Hi @vangheem and @bloodbare !

I'm opening this issue because something weird is happening with behaviors I defined in my app. I'm not sure if I'm not getting something about `AnnotationBehavior` or there is a bug...

**Problem**

Fields of type `ContextProperty` in a `AnnotationBehavior` doesn't return the value. I managed to reproduce it in this test: https://github.com/masipcat/guillotina/commit/5fff3cc125b68c8b78cdf7a6b1c8e8684288ed18

**Details**

After debugging a bit, I found that the value is stored in the `AnnotationData` (https://github.com/plone/guillotina/blob/master/guillotina/behaviors/instance.py#L76) because the attribute `comments` is not defined in the `__local__properties__`. The problem is that when the attribute `comments` is accessed returns the default value of the `ContextProperty` instead of the value in the annotation.

I followed the documentation on how to define a behavior and doesn't say anything about `__local__properties__` (https://guillotina.readthedocs.io/en/latest/developer/behavior.html#definition-of-a-behavior).

Could you clarify if this is a bug or just a missing line in the documentation?

Thank you all!

**Comment by vangheem** [comment]
hmmm, yes, `__local__properties__` is also necessary when using ContextProperty it seems.

I'm not sure it's a bug or not but that API really stinks. It would be great if using `ContextProperty` didn't require this.
