### ISSUE TITLE
Provide warning about insecure jwt secret for non-dev config

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#448]

**Comment by superit23** [comment]
Changing the algorithm in the config does not affect the algorithm used when the token is generated (`auth/__init__.py`) but only when it's validated (`auth/validators.py`). This causes all tokens to fail validation.
From `auth/__init__.py:43`
```python
jwt_token = jwt.encode(data, app_settings['jwt']['secret']).decode('utf-8')
```
From `auth/validators.py:99`
```python
validated_jwt = jwt.decode(
    token['token'],
    app_settings['jwt']['secret'],
    algorithms=[app_settings['jwt']['algorithm']])
```

**Comment by vangheem** [comment]
Fixed with https://github.com/plone/guillotina/pull/456
