### ISSUE TITLE
@wstoken should only be for authenticated users

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#449]

**Comment by AkshJain99** [comment]
@vangheem but how can we do that , if I understood it correctly we need to first authenticate the user and then make @wstoken for them isn't it?
what can be the initial step to do that

**Comment by vangheem** [comment]
By changing the permission required for it.

This was already done here: https://github.com/plone/guillotina/pull/451/files#diff-91cc4865390d052cf4e0aa3edd87a1afR46

**Comment by AkshJain99** [comment]
okay no problem!!

but can we have another issue , some easy one?
to work on?

**Comment by vangheem** [comment]
How about https://github.com/plone/guillotina/issues/447 ?

It's just moving the argon2 implementation from https://github.com/guillotinaweb/guillotina_hydraidp/blob/master/guillotina_hydraidp/utils.py#L34
to guillotina core.

and making it be used by default.

**Comment by AkshJain99** [comment]
okay I will work on this and submit a pr for this as soon as possible ?
btw thanks :)
