### ISSUE TITLE
Default Factory management

### ISSUE THREAD

**Issue by bloodbare** [plone/guillotina#453]
Default factory and default value on schema has some bugs:

- Right now on behaviors, it's only taking care of missing_value attribute.
- On context, it does not work properly (as sync/async factory)

In order to fix the issue I would like some feedback:

- On a GET operation, the default value should not be committed and only serialized on JSON serializer module.

- If we access the value on the code we should get the default value but add to the parent object if we are on a GET/HEAD operation.

**Comment by vangheem** [comment]
This fixed part of it: https://github.com/plone/guillotina/pull/455

However, we still need to advise the usage of it with behaviors.

**Comment by jordic** [comment]
I just remember a bit the issue.. but it still feels a bit odd for me to return a default value on a GET operation (while this value is not present on the source state, db)... anyway I think it work for us.

**Comment by vangheem** [comment]
@masipcat @jordic what is the status of this now? Can we close this you think?

**Comment by masipcat** [comment]
I remember two issues related with defaults.
 * [SOLVED] https://github.com/plone/guillotina/issues/393
 * [UNSOLVED/UNREPORTED]: When using AnnotationBehaviors the `default_factory` defined in the field is ignore and I need to define the `default_factory` in the `ContextProperty` as well. Example:

```python
class IImagesBehavior(Interface):

    index_field(
        "images",
        field_mapping={
            "type": "object",
            "enabled": False,  # index = False
            "properties": {},
        },
    )
    images = schema.Dict(
        key_type=schema.TextLine(),
        value_type=schema.TextLine(),
        required=False,
        default_factory=dict,
    #               -----^
    )


@configure.behavior(
    title="Images type map",
    provides=IImagesBehavior,
    marker=IImagesMarker,
    for_=IResource,
)
class ImagesBehavior(AnnotationBehavior):

    __local__properties__ = ("images",)

    images = ContextProperty("images", {})
    #                             -----^
```
