### ISSUE TITLE
Investigate a asgi based server

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#458]
pros/cons

**Comment by jordic** [comment]
Pros: 
- big move on python community (quark, django, starlette..). Interoperavility. Like wsgi on the pas
- http2 support throught hyper.
- Share middlewares, mount other services...
- separation of concerns. web framework vs web server
Cons:
- Maturity: asgi 2 to 3 (braking changes)

**Comment by masipcat** [comment]
+1

**Comment by cleder** [comment]
IIRC https://github.com/codelv/enaml-web does need an asgi server, so if there is any ambition to design an interface for guillotina in enaml this would be required (?)

**Comment by vangheem** [comment]
We've moving to move to asgi as it also helps us get to http2 support
