### ISSUE TITLE
Consider supporting pypy

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#459]
- add travis test target
- we'd need to always lag behind in our language upgrades to wait for pypy to finish implementation. In this case, we wouldn't be able to drop 3.6 until 3.7 is supported.

It would be really great to find a consistent way to test performance so we can identify the merits of supporting it.

**Comment by davisagli** [comment]
Also look at memory use in addition to performance

**Comment by vangheem** [comment]
Closing, we moved to 3.7... This isn't currently an option.
