### ISSUE TITLE
Guillotina command not waiting for all aio tasks to finish

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina#463]
Hi,

I'm running latest Guillotina with Guillotina Rediscache. I created a custom command to generate/modify some guillotina objects. The code looks like this:

```python
class ModifyObj(Command):
    description = "Modify obj"

    async def run(self, arguments, settings, app):
        request = self.request
        aiotask_context.set("request", request)

        async for _, _, container in get_containers(request):
            await modify_objects()
            await request._txn.commit()
```

After runnning the command the other instances still have the old object. The problem is that the command ends without waiting for all aio tasks to finish (https://github.com/plone/guillotina/blob/master/guillotina/commands/__init__.py#L211) so `RedisCache._synchronize()` is never called (https://github.com/masipcat/guillotina_rediscache/blob/master/guillotina_rediscache/cache_strategy.py#L163).

Is there any reason to just wait for tasks with `qualname` == `Pool.release`?

**Comment by masipcat** [comment]
Now I rewrote the previous code to:

```python
class ModifyObj(Command):
    description = "Modify obj"

    async def run(self, arguments, settings, app):
        request = self.request
        aiotask_context.set("request", request)

        async for _, _, container in get_containers(request):
            async with managed_transaction(request=request):
                await modify_objects_1()  # modifies a lot of objects
            # (implicit txn commit and close)

            async with managed_transaction(request=request):
                await modify_objects_2()  # modifies a lot of objects
            # (implicit txn commit and close)
```
But it seems that `managed_transaction()` isn't closing the transaction on `__aexit__()` so `RedisCache._synchronize()` never gets called.

**Comment by masipcat** [comment]
@vangheem is this a bug ^ ?

**Comment by vangheem** [comment]
I'm not sure what you mean about not closing the transaction.

It explicitly calls abort/commit https://github.com/plone/guillotina/blob/master/guillotina/transactions.py#L144

which should close the transaction..

If it is not, something must be wrong?

**Comment by masipcat** [comment]
Ok, I continued debugging the problem and I found the root cause. This is a simplified version of `modify_objects()`:

```python
def modify_objects():
    request = get_current_request()
    container = request.container
    ob = await container.async_get("ob")
    ob.change_field = True
    ob._p_register()

    assert ob._p_jar == request._txn  # different!
```

So, the problem is that `managed_transaction` cretes a new transaction inside the context manager and modifies `request._txn = new_txn` but doesn't modify `_p_jar` of guillotina objects stored in request attributes.

**Comment by vangheem** [comment]
Maybe we should make the `adopt_parent_txn` option default to True then...

Have you tried that?
