### ISSUE TITLE
OpenAPI 3 support

### ISSUE THREAD

**Issue by AkshJain99** [plone/guillotina#473]
Update endpoint definitions to work with openapi 3. For example, in the service definitions, they need to comply with new specification: https://github.com/plone/guillotina/blob/master/guillotina/api/behaviors.py#L17

**Comment by AkshJain99** [comment]
@vangheem can we also start implementing these task before gsoc result?

**Comment by vangheem** [comment]
ref: https://github.com/plone/guillotina/pull/544
