### ISSUE TITLE
Fix validation of object ids on transactions

### ISSUE THREAD

**Issue by bloodbare** [plone/guillotina#488]
When a ```create_content_in_container``` is done on a object there is not validation that the id has been already choosen and the conflict apears on serializing at the DB.

**Comment by bloodbare** [comment]
We need that async_get is able to retrieve objects from transaction objects and create_content_in_container validate against that objects also.

**Comment by jordic** [comment]
Are transaction objects shared across app instances?

**Comment by jordic** [comment]
Is the id (the oid) used? Why not relay the oid generator on a postgres sequence? I know that some part holds the parents sequence, but the second part could be and element from a sequence... (This way, the oid will be unique across transactions and instances.. )

**Comment by vangheem** [comment]
I think this is more about separating the transaction from the request object so we can interact the db more easily without needing the request on the task context.

I think in general, we should look into using the task context more generically instead of tacking everything onto the request all the time(maybe).

Let's try it and out and discuss the ramifications...

**Comment by jordic** [comment]
This will be awesome... (Anyway, any plans to just support 3.7? contextvars are ideal for this kind of things :)

**Comment by vangheem** [comment]
Yup, I'm open to requiring 3.7+ and using contextvars directly!

There is also a backport though if we wanted to maintain 3.6 support...

**Comment by bloodbare** [comment]
The issue its "simpler". If you create a two folders in the same transaction, check id is not validated. The validation is based on DB restriction.

```async_contains``` should check if there are objects on the transaction

**Comment by vangheem** [comment]
Updated title but Ramon is going to write a test to show the problem.

**Comment by vangheem** [comment]
We can close right?
