### ISSUE TITLE
Rename a folder will cause a sub-tree reindex

### ISSUE THREAD

**Issue by panjunyong** [plone/guillotina#494]
There is path index in catalog. If we rename a folder, then the sub tree need to be reindexed. It is quite heavy.

Just store a list of parent uuids will be much better:

- Rename a folder need not to reindex sub items.
- Path based search will easier with uuid

**Comment by vangheem** [comment]
That's a good idea!

It might make query interface a little difficult to grok.

I also wonder how this might affect things when you move content to a new location.

**Comment by panjunyong** [comment]
It is easy to batch update the parent_uuids index by query.

The difficult thing is how to batch update the security info. We can diff the security info and use a script to apply the sub tree. To make it possible, we need store more acl info in ES. This can be described in a another issue later.

**Comment by vangheem** [comment]
Yup, if you go the route of storing a representation of the acl in elasticsearch, we have a lot of options available to use to do update by queries.

This would help with moves, rename and security changes.

**Comment by vangheem** [comment]
Do you have any further investigation into this issue?

I'm in cleaning mode for stale issues. Feel free to reopen with updates but we're open to PRs and more details!
