### ISSUE TITLE
 get_object_by_oid load all the object's parents

### ISSUE THREAD

**Issue by panjunyong** [plone/guillotina#495]
In the current implementation, get_object_by_oid load all the object's parents. It is a little expensive.

Although we can cache objects from redis, we can fix it better.

when load from get_object_by_oid, we can just use a lazy parent:

    obj.__parent__ = LazyResource(obj)

The LazyResource is loaded from db or cache when required.

**Comment by vangheem** [comment]
This might be difficult because of the constraints of asyncio--we never interact with the db in a blocking, synchronous way.

**Comment by panjunyong** [comment]
For example, the LazyResource can override the __getattr__ method:

```
def __getattr__(self, name, default):
     if not self._loaded:
          # async wait load from db
     return getattr(self.obj, name, default)
```

**Comment by vangheem** [comment]
Unfortunately, you can't make `__getattr__` async though and we can't call async code from non-async func.

This is why some of our APIs maybe feel a bit odd compared to zodb. zodb would load objects synchronously when attributes were accessed. We can not do that.

For example, loading behavior data requires the extra `await beh.load()` -- https://github.com/plone/guillotina/blob/master/guillotina/utils/content.py#L193

Maybe we add a parameter to `get_object_by_oid` to tell it not to load parent objects. Then, if you decide you need them, we can add utility that will back fill all parent objects.

I'm open to additional ideas though.

**Comment by panjunyong** [comment]
How about hide ``__parent__`` attribute and use ``obj.get_parent()`` instead?

``get_parent`` method can be  async.

**Comment by vangheem** [comment]
We can look into doing this.

FWIW, I don't even think that `get_object_by_oid` is used internally.

Changing how we do `__parent__` would break a lot of APIs. I would prefer to provide a b/w compat way to do this.

FWIW, redis with in-memory cache is very fast. I don't know your data structure though so maybe this provides a lot of performance improvement.

**Comment by panjunyong** [comment]
Can we make ``__parent__`` a property?

    `   __parent__ = property(get_parent, set_parent)`

**Comment by vangheem** [comment]
and make `get_parent, set_parent` async?

That would mean we'd have an api that would look like

```
await ob.__parent__
```

I think I'd prefer the `async def get_parent` approach over this.

**Comment by vangheem** [comment]
I don't know your use-case, but I would recommend writing your own internal get_object_by_uid that doesn't load parents.

**Comment by vangheem** [comment]
I'm closing for now.

The only option so far would be to change the API to make the `__parent__` attribute be `async def get_parent()`

I'm not very keen on making this drastic of a change to the API. For us, the in memory cache makes the parent lookup very fast.

I'm still open to more discussion if you are interested but closing for now.
