### ISSUE TITLE
Each db should have its own oid_generator

### ISSUE THREAD

**Issue by panjunyong** [plone/guillotina#496]
Now only one oid_generator is allowed for all db and storage. This policy make it hard to extend.

For example, to make db faster, we are trying another pgsql storage implementation, which stores oid as integer. The uuid can be still a string, just like '1235223'. We convert the uuid to integer when save. This need an integer-based uuid generator.

For cockroach db, the default oid_generator is  ok, which stores parent prefixes. 

So, different DBs may have different oid generators. But in the config yaml, only one oid_genterator is allowed. So I think the oid generator should belong to each database's configuration.

But this change will bring another break: the uuid will not be unique between databases.

But since the container object means a site, it is enough that uuid is unique in the container. Different db has different uuid system is ok.

**Comment by vangheem** [comment]
FWIW, I'm completely fine with changing this.

A good compromise would be to move the configuration to be a database configuration instead of a global configuration.

**Comment by vangheem** [comment]
I'm open to PRs related to this.

I think being able to configure the id generator on the storage makes most sense.

Closing for now!
