### ISSUE TITLE
state field need to support live migrations

### ISSUE THREAD

**Issue by panjunyong** [plone/guillotina#500]
Now we use python pickle protocol for the `state` field in the db. 

But pickle is not a ideal serializing method for a since it is restricted to python language and bound to the code. Other serialize method like josn pickle is more explicit but slow. We have to choose pickle method but may change in the future.

So we need to design more for the future migration. With BIG data, migrating may cost a lot of time, and we need live migration. Both old and new data format may exists.

A new `state_format` field for the state field can solve the problem. 

Or just a bool `state_migrate_flag` field is ok, since only 2 formats exists in the db at most.

**Comment by vangheem** [comment]
I'm open to accepting PRs related using a `state_format` field.

Also, might be worth integrating in your own addon first and then making a PR against it.

Closing for now. Please reopen if there is more discussion/questions/interest.
