### ISSUE TITLE
Why isn't cookiecutter part of the setup.py?

### ISSUE THREAD

**Issue by pigeonflight** [plone/guillotina#503]
In reading the docs there is always a separate step to `pip install cookiecutter`.
Is there a reason that cookiecutter can't just be added to the setup.py as a dependency?

**Comment by vangheem** [comment]
I prefer things to be optional dependencies when possible.

If you need to use a template, it seems fine to then just do a `pip install cookiecutter`.

**Comment by vangheem** [comment]
We have other optional dependencies as well: `aiohttp_reload`, `line_profiler`, `aiomonitor`

**Comment by pigeonflight** [comment]
So it's just a preference.
.... and you don't like using "extras_require"  in setup.py for this type of scenario?

**Comment by vangheem** [comment]
extras are fine!

**Comment by vangheem** [comment]
I'm closing issue. Feel free to make PR to add extras and I will merge!
