### ISSUE TITLE
Proposal: move db_users inside guillotina.contrib

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#564]
Seems natural, as we had done similar with cache or catalog, on the end doesn't make too much sense for developer experience to install an extra package for something as core as user system. 
It also allows us to keep the version dep stable: every new guillotina is tested with this basic user system. Also if we plug basic user management into executioner.. makes lot of sense.

**Comment by vangheem** [comment]
I'm okay with this. Would you be willing to make the PR to make this happen?

**Comment by jordic** [comment]
yes

**Comment by bloodbare** [comment]
Great! We will keep alpha until then!

**Comment by jordic** [comment]
will try to do it asap

**Comment by vangheem** [comment]
Closing, 5.x final release done.
