### ISSUE TITLE
Pubsub. drivers

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#565]
With G5 we are introducing the pubsub utility, but it depends on a driver that is not documented. 
The redis driver I think that makes more sense to have it on the pubsub side. 

also I think we should provide and interface to document the driver.

**Comment by bloodbare** [comment]
I know that we need to provide documentation about drivers. I don't think that makes sense to have it on the pubsub side as its used for so many components. I've thought about moving them to utilities but there are some cons on the  bootstrap lifecycle dependency. We can discuss about it.

Some docs:
https://github.com/plone/guillotina/blob/master/docs/source/contrib/pubsub.md
