### ISSUE TITLE
How to enforce single item of a particular type exists in an Container/Folder type

### ISSUE THREAD

**Issue by harwee** [plone/guillotina#573]
I have some custom types which i want to add to a container or a folder but only once, I am fine with limiting the creation of these items by not changing the id but I cannot find a way to enforce this while creating the content type. Is there a way to hard code the id of the content type?

**Comment by vangheem** [comment]
you could override the `id` property for the content type maybe?

Maybe something like this in your content type?

```
    def set_id(self, id_):
        if id_ != 'myid':
            raise ConflictIdOnContainer(f'Invalid ID: {id_}')
        if id_ is not None:
            self.__name__ = id_

    def get_id(self):
        return self.__name__

    id = property(get_id, set_id)
```

**Comment by harwee** [comment]
That did the trick! I think it would be better if there is a configuration setting to make it behave like a singleton class.
