### ISSUE TITLE
Custom Containers/Enforce contenttype restrictions on a container

### ISSUE THREAD

**Issue by harwee** [plone/guillotina#574]
I tried looking in the documentation but I couldn't find much about Containers. Is there any way to create a custom container type or enforce content type restrictions on a container?

**Comment by vangheem** [comment]
You can provide a constrain types adapter. Will something like this work for you? https://github.com/plone/guillotina_cms/blob/master/guillotina_cms/content/contraintypes.py

**Comment by harwee** [comment]
That code can help enforce restrictions based on name, but it will be messy to write, is there any way to subclass `IContainer` and create a new container type something like this?

    class ICustomContainer(IContainer):
        """Custom Container Interface"""

    @configure.contenttype(
        type_name="CustomContainer",
        schema=ICustomContainer,
        allowed_types=['CustomTypes'],
        )
    class CustomContainer(Container):
        "Container for CustomTypes"

So that I can do something like this?

    @configure.adapter(
        for_=(ICustomContainer, Interface),
        provides=IConstrainTypes)
    class CustomContainerAllowedTypes(FTIConstrainAllowedTypes):

        def get_allowed_types(self) -> list:
            return [...]

**Comment by vangheem** [comment]
Yup, you can customize the `container_types` app_setting:

in json settings:
```
{
"container_types": ["Container", "MyContainerType"]
}
```

**Comment by harwee** [comment]
I did everything but couldn't find that i need to add it to the configuration file. It works now thanks for the help!
