### ISSUE TITLE
`@search` should support an option to get only direct children

### ISSUE THREAD

**Issue by ebrehault** [plone/guillotina#619]
We use the `@search` endpoint in Executioner to get the container items, but it is actually returning the direct children but also all the sub-children (so at the moment the navigation in Executioner is a total mess).

We need either a boolean option `restrictToDirectChildren` either a number option `path`.

**Comment by vangheem** [comment]
Is there a bug in our query interpretation? Maybe you should be doing a query by parent_uuid instead?

**Comment by ebrehault** [comment]
I do not think there is a bug. Our current way to load children for a given container is:
```
POST ${containerPath}/@search
{_from: 0}
```

So I guess we should just do:
```
POST ${containerPath}/@search
{_from: 0, query: {parent_uuid: ${containerUuid}}}
```

At the moment, we are just managing the full navigation by parent paths, and I don't feel like I will manage also their uuids (I am refactoring the entire thing with ngrx state manager anyway, so it will fix that problem anyway)
