### ISSUE TITLE
Use built-in swagger authentication schemes

### ISSUE THREAD

**Issue by vangheem** [plone/guillotina#622]
Let's remove the old integration we used for authenticating requests and go to a more default swagger UI experience.

The latest swagger has configuration called `requestInterceptor`.

With that, we can provide our overridden authentication headers.

See for simple example: https://github.com/swagger-api/swagger-js/issues/1124

So we'll use this button:

<img width="248" alt="Screen Shot 2019-08-04 at 4 14 24 PM" src="https://user-images.githubusercontent.com/524413/62428742-ff0de980-b6d2-11e9-936d-c586a7cddc3e.png">

<img width="775" alt="Screen Shot 2019-08-04 at 4 14 28 PM" src="https://user-images.githubusercontent.com/524413/62428743-0208da00-b6d3-11e9-8ae9-cc9c2e9e0e20.png">

To also override the auth headers to get the swagger definition.

This should really cleanup our swagger integration.

Let me know if you have questions because I can dig into this more as well. Here is what I did when playing with it: https://github.com/plone/guillotina/commit/64a9406381a5954c5ee749b10f7cf15ea8bf755b

**Comment by vangheem** [comment]
If that doesn't work, look at how the current download url is done: https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/download-url.js

It's very simple and could easily be augmented to replace how the current implementation is done to make it work nicer.

**Comment by karannaoh** [comment]
I have already tried this, now also instead of `requestInterceptor` I am using 
`configs: {
            preFetch: function(req) {
                req.headers["Authorization"] = that.authenticator.getAuthToken();
                return req;
            }
          }`
which is serving the same pourpose.
[link to code](https://github.com/plone/guillotina/blob/74004667531cda503bc88e3d59fa74e44e30e019/guillotina/contrib/swagger/static/integration.js
)
the problem which I was facing was adding custom event to buttons login logout just logout was broken which is why I used the previous thing. And this was much more hacky

**Comment by vangheem** [comment]
Yes, let's try to use the regular auth integration still.

This data is stored(maybe need to do tricks to access it, maybe with redux)--we should be able to write integration that pulls the data correctly from there instead of doing our current implementation.

Review the code here: https://github.com/swagger-api/swagger-ui/tree/master/src/core/components/auth

The authentication details are stored.

Let's pull from these values and use with the preFetch or requestInterceptor.

We shouldn't need to intercept button events or anything like that--just need to pull current values from swagger authentication.

**Comment by karannaoh** [comment]
another problem which is there is base URL will have @swagger at the end of it

**Comment by karannaoh** [comment]
#629
