### ISSUE TITLE
Configuration training errors

### ISSUE THREAD

**Issue by khssnv** [plone/guillotina#647]
Hello.

I'm walking through [training](https://guillotina.readthedocs.io/en/latest/training), there are a few issues:

1. At [this step](https://guillotina.readthedocs.io/en/latest/training/configuration.html#configuration-file) an attempt fails with an error `asyncpg.exceptions.InvalidAuthorizationSpecificationError: role "postgresql" does not exist`. After replace `postgres` to `guillotina` in connection string works fine.
2. At [this step](https://guillotina.readthedocs.io/en/latest/training/configuration.html#installing-applications) server startup fails with an error `ModuleNotFoundError: No module named 'guillotina.contrib'`.

<details>
  <summary>My setup</summary>

```console
(venv-py37) user@pc ~/Workspace
$ pip show guillotina
Name: guillotina
Version: 4.9.6
Summary: asyncio REST API Resource database
Home-page: https://github.com/plone/guillotina
Author: Ramon Navarro Bosch & Nathan Van Gheem
Author-email: ramon@plone.org
License: BSD
Location: ...
Requires: python-dateutil, jsonschema, jwcrypto, setuptools, ujson, zope.interface, pyjwt, pycryptodome, asyncpg, cffi, aiotask-context, lru-dict, aiohttp, PyYAML
Required-by:
(venv-py37) user@pc ~/Workspace
$ python -V
Python 3.7.4rc1
```
Current `guillotina` version at https://pypi.org/project/guillotina/
![image](https://user-images.githubusercontent.com/833019/63651323-425cf480-c775-11e9-8649-be8ab4438524.png)

</details>

**Comment by khssnv** [comment]
Seems like docs outruns releases. I've find *Configuration* step for `guillotina 4.9` [here](https://github.com/plone/guillotina/blob/76fd447dcd0736e2d150812ef95cae3fc4cb2483/docs/source/training/configuration.md).

**Comment by karannaoh** [comment]
Can you tell what config.yaml you are using?

**Comment by vangheem** [comment]
1) Thank you for the report! I think this should fix it: https://github.com/plone/guillotina/pull/648
2) @khssnv you are following the docs for guillotina 5 but are running guillotina 4.
