### ISSUE TITLE
buildout.cfg

### ISSUE THREAD

**Issue by svx** [plone/guillotina#659]
Currently, there are two files with references to `buildout.cfg`

```shell
grep -ir "buildout.cfg"
MANIFEST.in:include buildout.cfg
buildout-docs.cfg:extends = buildout.cfg
```

But I am not able to find the `buildout.cfg`.

Was `buildout.cfg`. used in the past, but not anymore?
If so, should I open a PR which removes `buildout-docs.cfg` and cleans up `MANIFEST.in` ?

:)

**Comment by vangheem** [comment]
Please remove any reference to buildout! That is long gone!
