### ISSUE TITLE
Fix docs patch dict field

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#674]
![Captura de pantalla de 2019-09-18 13-29-49](https://user-images.githubusercontent.com/64216/65144853-7ea00f80-da18-11e9-8c74-de52615f2826.png)

"value" refers to the field do you want to patch

**Comment by vangheem** [comment]
This was fixed right? I'm closing :)

**Comment by masipcat** [comment]
No, it's not. We think the name "values" is kinda confusing because isn't clear that is the field name...
(From doc: https://guillotina.readthedocs.io/en/latest/developer/fields.html#patch-field-list)
```json
{
    "values": {
        "op": "append",
        "value": "foobar"
    }
}
```
I think something like this would be easier to understand:
```python
from zope.interface import Interface
from guillotina.fields import PatchField
from guillotina import schema

class IMySchema(Interface):
    my_list_field = PatchField(schema.List(
        value_type=schema.Text()
    ))
```

```json
{
    "my_list_field": {
        "op": "append",
        "value": "foobar"
    }
}
```

**Comment by vangheem** [comment]
Yes, sorry, I just noticed as well that PR was never merged.

**Comment by masipcat** [comment]
offtopic: I think that we could add as well the operation 'multi', so we can specify different operations at once. Something like:

```json
{
	"my_list_field": {
		"op": "multi",
		"value": [{
			"op": "remove",
			"value": "foo"
		}, {
			"op": "append",
			"value": "bar"
		}]
	}
}
```

Makes sense?

**Comment by vangheem** [comment]
Yup. Sounds good to me.

It should be quite simple to implement.
