### ISSUE TITLE
Problems configuring cache

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina#677]
I'm trying to configure the in-memory cache in guillotina 5:

> In-memory with redis invalidations
>
> Object invalidations are coordinated across Guillotina instances; however, pushing object data into and out of redis can be heavy on redis. Sometimes, an in-memory cache configuration but using redis only for pubsub invalidations provides the best performance.
>```yaml
> applications:
>- guillotina.contrib.redis
>- guillotina.contrib.pubsub
>- guillotina.contrib.cache
>cache:
>  driver:
>  updates_channel: guillotina
>  push: false
>-
>```

*source: https://guillotina.readthedocs.io/en/latest/contrib/cache.html#in-memory-with-redis-invalidations*

but I'm getting this error:

```
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/guillotina/factory/app.py", line 381, in cleanup_app
    await close_utilities(app)
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/guillotina/factory/app.py", line 389, in close_utilities
    await root.del_async_utility(key)
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/guillotina/factory/content.py", line 97, in del_async_utility
    await lazy_apply(utility.finalize, app=self.app)
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/guillotina/contrib/cache/utility.py", line 56, in finalize
    await self._subscriber.unsubscribe(settings["updates_channel"], self._uid)
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/guillotina/contrib/pubsub/utility.py", line 83, in unsubscribe
    raise NoPubSubDriver()
guillotina.contrib.pubsub.exceptions.NoPubSubDriver
```

If I set the property `driver` to `"guillotina.contrib.redis"` doesn't crashes. It's an error in the documentation or it's a bug?

Thank you!

**Comment by vangheem** [comment]
This the only error? It's only happening on shutdown then?

That would seem to indicate that maybe pubsub never got configured.

But that is weird because if there was a config problem the initialize should be throwing an error.

Is there more to the stacktrace maybe?

**Comment by vangheem** [comment]
btw, your `NoPubSubDriver` error is on pubsub, not cache so it's weird that you're getting that error.

Can you make sure `load_utilities` has the

```
"load_utilities": {
        "guillotina_pubsub": {
            "provides": "guillotina.interfaces.IPubSubUtility",
            "factory": "guillotina.contrib.pubsub.utility.PubSubUtility",
            "settings": {"driver": "guillotina.contrib.redis"},
        }
    }
```

entry on startup?

Maybe you're overriding that entire value?

**Comment by masipcat** [comment]
I found the problem. As you suggested, `guillotina_pubsub` wasn't present in the (testing) settings. I added it, and then I was missing the configuration for `redis` and `cache`... Now the tests are passing! but when I run the server and I after a minute I kill it, I get this error:

```
msgpack not installed, MsgPackSerializer unavailable
No cache utility configured
No cache utility configured
No cache utility configured
Adding guillotina.queue : guillotina.interfaces.IQueueUtility
Adding guillotina.jobpool : guillotina.interfaces.IAsyncJobPool
Adding guillotina_pubsub : guillotina.interfaces.IPubSubUtility
Adding guillotina_cache : guillotina.interfaces.ICacheUtility
Adding catalog : guillotina_elasticsearch.interfaces.IElasticSearchUtility
Adding s3 : guillotina_s3storage.interfaces.IS3BlobStore
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
^CRemoving guillotina.queue
Removing guillotina.jobpool
Removing region
Removing guillotina_pubsub
Unhandled exception with pubsub. Sleeping before trying again
Traceback (most recent call last):
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/guillotina/contrib/pubsub/utility.py", line 47, in real_subscribe
    channel = await self._driver.subscribe(channel_name)
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/guillotina/contrib/redis/driver.py", line 110, in subscribe
    channel, = await self._pubsub_subscriptor.subscribe(channel_name)
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/aioredis/commands/pubsub.py", line 31, in subscribe
    conn.execute_pubsub(b'SUBSCRIBE', channel, *channels),
  File "/home/jordi/gits/api/g5venv/lib/python3.7/site-packages/aioredis/connection.py", line 363, in execute_pubsub
    raise ConnectionClosedError("Connection closed or corrupted")
aioredis.errors.ConnectionClosedError: Connection closed or corrupted
Removing guillotina_cache
```

**Comment by vangheem** [comment]
ahh, k. Can you look at this and see if it helps? https://github.com/plone/guillotina/pull/678

**Comment by vangheem** [comment]
Merged and released!
