### ISSUE TITLE
Python 3.8 and pickles

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina#722]
I started testing Guillotina on Python 3.8. Python 3.8 introduced pickle protocol v5. Since guillotina is configured to use `pickle.HIGHEST_PROTOCOL`, all the objects serialized with py3.8 aren't compatible with py3.7 so is not possible to run instances of guillotina with different python versions side by side.

Thoughts about this:
1. Maybe using HIGHEST_PROTOCOL its a bit dangerous and we could choose the protocol version based on the python versions we support (for instance, G5 supports python 3.7 and 3.8, so we could choose to use protocol v4). We can upgrade the protocol version on G6 or G7.
2. Allow to configure protocol version through configuration (so the user can choose to use HIGHTEST_PROTOCOL if he wants)

cc/ @vangheem @bloodbare

**Comment by vangheem** [comment]
ouch, yes, I agree.

Let's by default use v4 and then make it configurable.

We'll also need to be careful to consider this when(if) we deprecate a protocol.
