### ISSUE TITLE
PubSubUtility doesn't recover after a redis restart

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina#746]
The current implementation just logs the following error but doesn't reinitializes the connection.

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/guillotina/contrib/pubsub/utility.py", line 48, in real_subscribe
    channel = await self._driver.subscribe(channel_name)
  File "/usr/local/lib/python3.7/site-packages/guillotina/contrib/redis/driver.py", line 110, in subscribe
    (channel,) = await self._pubsub_subscriptor.subscribe(channel_name)
  File "/usr/local/lib/python3.7/site-packages/aioredis/commands/pubsub.py", line 31, in subscribe
    conn.execute_pubsub(b'SUBSCRIBE', channel, *channels),
  File "/usr/local/lib/python3.7/site-packages/aioredis/connection.py", line 363, in execute_pubsub
    raise ConnectionClosedError("Connection closed or corrupted")
aioredis.errors.ConnectionClosedError: Connection closed or corrupted
```

Log:
```
Unhandled exception with pubsub. Sleeping before trying again
```

**Comment by vangheem** [comment]
It is in a `while channel_name in self._subscribers:`

Shouldn't it retry?

**Comment by masipcat** [comment]
Yeah. All I know right now is the guillotina pod "was failing" until we restarted the instance... I'll reproduce this locally and see what happens.

**Comment by masipcat** [comment]
https://aioredis.readthedocs.io/en/latest/api_reference.html#aioredis.ConnectionsPool.execute_pubsub

> There is no auto-reconnect for Pub/Sub connection as this will hide from user messages loss.

Any idea on how to fix this on guillotina? or at least, make sure that PubSub utility doesn't goes to a unresponsive state without recovering.

**Comment by masipcat** [comment]
Maybe we can try this: https://github.com/aio-libs/aioredis/issues/409#issuecomment-399094609

**Comment by vangheem** [comment]
I'm not sure.

We already do this:

```
async def _listener(self, channel: aioredis.Channel):
        while await channel.wait_message():
            msg = await channel.get()
            yield msg
```

Can we try this...

- do not use the pool for pub/sub
- on any error, close the connection and create a new one

**Comment by masipcat** [comment]
I think we can close this issue for now
