### ISSUE TITLE
Be able to autodiscover dbs and containers per instalation

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#752]
With this feature,
we can show on login screen a mechanism to select the instance where you want to `@login`

If the user is `root` or has admin permissions, he will go anyway to the root.

**Comment by vangheem** [comment]
I think that it's probably best to not have it be auto discovery as you'd be revealing things you might not want to do.

I think we should do 2 things...
- provide endpoint to list dbs. Use permission to lock this dude
- be able to customize permissions with configuration you could expose that endpoint for your use case

**Comment by jordic** [comment]
Just thinking on it, it's something I want to add it to the login screen on guillotina_react:

![login](https://user-images.githubusercontent.com/64216/70411229-e5e6c200-1a51-11ea-95a7-2c8091b98bc2.png)

Perhaps, the best solution is to just ship guillotina react as pip package, and make the autodiscover an opt-in feature throught settings:

`
guillotina_react: {
   autodiscover: True,
   home_selector: 'user_home'
}   
`
