### ISSUE TITLE
User and Group from dbUsers should be restricted to UserFolder/GroupFolder

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#774]
Doesn't make any sense that and admin could add a user content type everywhere.. 

https://github.com/plone/guillotina/blob/master/guillotina/contrib/dbusers/content/users.py#L52

**Comment by jordic** [comment]
@lferran we need to add something here, no?

**Comment by lferran** [comment]
@jordic I think this issue can be closed. I already fixed in this PR: https://github.com/plone/guillotina/pull/800/files#diff-35da10df07a75358094b17645171e9b0R195
