### ISSUE TITLE
help with @upload

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#798]
It's not so clear how it works from docs:
- first try with a form upload from us (the usual way) doesn't worked. 
Thought I should send the binary on a payload day key.. but which version? 
Any example elsewhere where I can check how the API works from a client is browser app?

**Comment by vangheem** [comment]
For `@upload`, just send the binary data as the body--that's it.

https://guillotina.readthedocs.io/en/latest/rest/item.html#patch--(db)-(container)-(id)-@upload-(field_name)

It's also the same with postman--just select the file you want to upload and it sends it as the body of the request.

**Comment by jordic** [comment]
Yup, found it.. it's more a thing around file objects and js.. also found  that grange-core is sending them as uuencode strings.. any reason for that? 
https://github.com/guillotinaweb/grange-core/blob/master/projects/grange-core/src/lib/resource.service.ts#L101

Not pretty sure but I also have to fix the content-type, with a header.
Later after downloading the file I also has to revert the uuencode thing.. :/

**Comment by vangheem** [comment]
it's not converting to unicode, it's converting to base64.

I imagine that's when you want to update the field value directly in a PATCH instead of using the `@upload` endpoint? \cc @ebrehault

**Comment by jordic** [comment]
yup, thought the gmi should work directly with bytes.. (closing for the moment)
