### ISSUE TITLE
IMultiAttachment. Delete attachment

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#801]
Seems like the multiattachment behavior doesn't allow to delete files.
It could be awesome to just have the endpoint

`DELETE context/@upload/field/file`

On the gmi, I have a widget like this for IMultiAttachment:

![Captura de pantalla de 2019-12-26 12-03-14](https://user-images.githubusercontent.com/64216/71473573-cb457480-27d7-11ea-9f56-319f3030bdf9.png)

The feature, will allow to remove keys from the behavior

**Comment by vangheem** [comment]
Definitely! I agree.

**Comment by masipcat** [comment]
I see that `IFileStorageManager` doesn't defines a `delete()` method. Can we add it to the interface?

I can take care of this issue if you both agree.

**Comment by vangheem** [comment]
yes please, we need this.
