### ISSUE TITLE
Pg catalog id__in

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#825]
Searching a substring of an id doesn't work:

something like: id__in = 'asdf' doesn't work, the query for strings, should be something like

```sql
select id from guillotina.objects where json->>'id' like '%value%';
```

If @bloodbare agrees will try to add this to the parser.

**Comment by vangheem** [comment]
I'm not sure. It's supposed to be like keyword. What is the current way to do full text? What if you want to do key word and full text search on a field (textkeyword I think)? Taking over the "in" keyword would prevent this?

**Comment by jordic** [comment]
Got it, coool!
Following the same approach, if exists an `__starts`, perhaps we should add a `__contains`? and an `__ends`?

**Comment by jordic** [comment]
That's also wired, using the catalog to lookup an object by id,
`tool.query(container, {"type_name": "Source", "id": "xxxx"})` results in a query like:

```select id, zoid, json from guillotina.objects where json->'id' ? 'xxxxx'```

So sorry, I'm completly lost, thought it has to be something like:
```select id, zoid, json from guillotina.objects where json->>'id' = 'xxxxx'```

It has to be something I'm doing wrong, but anyway, it's hard to understand it...

**Comment by jordic** [comment]
OMG, got it, 
when I'm using the catalog from a command, if not provided it's using anonymous user... 
The behavior it's good (secure by default), but thought it should be documented anywhere... 
I specially think, that this part (mostly) catalog, that it's so important to work with guillotina (as a data framework, should be better documented)
