### ISSUE TITLE
If no request is provided pg catalog fails

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#826]
If we try to use the catalog on a Command, and we don't provide a mock request... the query catalog fails.. This is the wrong line:

https://github.com/plone/guillotina/blob/master/guillotina/contrib/catalog/pg.py#L613

Not sure why, if it doesn't find a request it resets the current transaction `txn`. That's wired, because if the exception is shadowed, but the db connection is reset, it will fail later... 

Also, seems like, it needs the request, just to serialize full objects? 
Thought we need to talk a bit about this part.

**Comment by vangheem** [comment]
That's a bug!
