### ISSUE TITLE
Obsolte code on shell command

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#827]
https://github.com/plone/guillotina/blob/master/guillotina/commands/shell.py#L126

Seems like it's not need, the signature for the login func just calls set_authenticated_user
```
def set_authenticated_user(user):
    if user is not None and not isinstance(user, AnonymousUser):
        policy = get_security_policy(user)
        policy.invalidate_cache()
        if hasattr(user, "roles") and "guillotina.Authenticated" not in user.roles:
            user.roles["guillotina.Authenticated"] = 1
    task_vars.authenticated_user.set(user)
```
https://github.com/plone/guillotina/blob/master/guillotina/auth/utils.py#L34

I don't see a password anywhere, thought could be safely removed

**Comment by vangheem** [comment]
yup, I agree!
