### ISSUE TITLE
Problems with optimized_lookup()

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina#832]
I was trying 6.0.0a6 in my api and I get the following error when running the tests:

```
{'message': "Expected <class 'float'> but found <class 'int'>.", 'value': 1}
```
The problem is here:
https://github.com/plone/guillotina/blob/3258dec0b50e9b4ab703478321cd29c49f4a985d/guillotina/json/deserialize_value.py#L48

This was allowed in the past. Is this behavior intended?

**Comment by vangheem** [comment]
ahh, I guess I didn't realize this was used and is possible. I'll try and fix tonight.

**Comment by masipcat** [comment]
Nice :) Thank you

**Comment by vangheem** [comment]
PR for this: https://github.com/plone/guillotina/pull/833
