### ISSUE TITLE
Docker Image Failing experience

### ISSUE THREAD

**Issue by bloodbare** [plone/guillotina#920]
- Would be great that a default configuration is not needed and there is a default command on the docker image to start a dummy configuration.

- Once it starts with a dummy configuration accessing any jsapps fails. I think is related with the headers sent by ASGI server.

To reproduce:

Running:

`docker run -p 8080:8080 -it plone/guillotina g -c /app/config-dummy.yaml`

Accessing:

`http://localhost:8080/+manage/`

**Comment by masipcat** [comment]
> Once it starts with a dummy configuration accessing any jsapps fails. I think is related with the headers sent by ASGI server.


Yes, we are sending application/octet-stream instead of text/html. I'll fix it later
